name: Security Scan
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
jobs:
  security:
    timeout-minutes: 10
    permissions:
      contents: read
      security-events: write
    environment:
      name: test-confluencer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/ruby@v1.1.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}